Repository tclerico/iCook, pull requests merged in 2019-03, with the labels that each got.

#22 created fridge class
  src/main/java/edu/ithaca/goosewillis/iCook/Fridge.java
Labels: in progress

#23 Get ingredients from fridge #6
  pom.xml
  src/main/java/edu/ithaca/goosewillis/iCook/Fridge.java
  src/test/java/edu/ithaca/goosewillis/iCook/FridgeTest.java
Labels: in progress

#27 Search for ingredient
  src/main/java/edu/ithaca/goosewillis/iCook/Recipe.java
  src/test/java/edu/ithaca/goosewillis/iCook/RecipeTest.java
Labels: review

#28 Ingredient
  src/main/java/edu/ithaca/goosewillis/iCook/Ingredient.java
  src/test/java/edu/ithaca/goosewillis/iCook/IngredientTest.java
Labels: review

#31 working cookbook
  cookbook.json
  pom.xml
  src/main/java/edu/ithaca/goosewillis/icook/Main.java
  src/main/java/edu/ithaca/goosewillis/icook/cookbook/CookBook.java
  src/main/java/edu/ithaca/goosewillis/icook/cookbook/CookbookSerializer.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/Recipe.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/ingredients/DietType.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/ingredients/Ingredient.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/ingredients/IngredientSerializer.java
Labels: team review

#32 Onetray
  src/main/java/edu/ithaca/goosewillis/icook/CLI.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/Recipe.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/ingredients/Ingredient.java
  src/test/java/edu/ithaca/goosewillis/icook/IngredientTest.java
Labels: team review

#33 Cli
  cookbook.json
  fridge.json
  src/main/java/edu/ithaca/goosewillis/icook/CLI.java
  src/main/java/edu/ithaca/goosewillis/icook/Main.java
  src/main/java/edu/ithaca/goosewillis/icook/cookbook/CookBook.java
  src/main/java/edu/ithaca/goosewillis/icook/fridge/Fridge.java
  src/main/java/edu/ithaca/goosewillis/icook/fridge/FridgeSerializer.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/Recipe.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/ingredients/Ingredient.java
  src/main/java/edu/ithaca/goosewillis/icook/recipes/ingredients/IngredientSerializer.java
Labels: team review
